---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name }} | Create bin directory"
  ansible.builtin.file:
    mode: "700"
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory 

- name: "{{ role_name }} | Install"
  ansible.builtin.get_url:
    dest: "{{ ansible_user_dir }}/.local/bin/devtunnel"
    mode: "700"
    url: https://aka.ms/TunnelsCliDownload/linux-x64
