---
- name: "Kanshi | Fedora | Install"
  ansible.builtin.dnf:
    name:
      - kanshi
    state: present
  become: true

- name: "Kanshi | Fedora | Start"
  ansible.builtin.systemd_service:
    daemon_reload: yes
    enabled: yes
    name: kanshi
    scope: user
    state: started
