---
- name: "System | {{ ansible_distribution }} | Create ~/.config/environment.d"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/environment.d"
    mode: "755"
    state: directory

- name: "System | {{ ansible_distribution }} | Set locale"
  ansible.builtin.lineinfile:
    create: true
    dest: "{{ ansible_user_dir }}/.config/environment.d/10-locale.conf"
    line: "{{ item.key | upper }}={{ item.value }}"
    mode: "644"
    regexp: "^{{ item.key | upper }}="
  loop: "{{ system.locale | dict2items }}"

- name: "System | {{ ansible_distribution }} | Set keyboard"
  ansible.builtin.lineinfile:
    create: true
    dest: "{{ ansible_user_dir }}/.config/environment.d/11-keyboard.conf"
    line: "{{ item.key | upper }}={{ item.value }}"
    mode: "644"
    regexp: "^{{ item.key | upper }}="
  loop: "{{ system.keyboard | dict2items }}"
