---
- name: "{{ role_name }} | {{ ansible_facts.distribution }} | Install"
  ansible.builtin.apt:
    name:
      - zoxide
    state: present
  become: true
  when: ansible_facts.distribution_version >= '21.04'
