---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name }} | Create desktop shortcut for each profile"
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.local/share/applications/microsoft-edge-{{ profile.name }}.desktop"
    mode: "600"
    src: edge-profile.desktop.j2
  loop: "{{ edge.profiles }}"
  loop_control:
    loop_var: profile
  when: edge.profiles is defined
