---
- name: "Alacritty | Checking for distribution config: {{ ansible_facts.distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts.distribution }}.yml"
  register: distribution_config

- name: "Alacritty | Run tasks: {{ ansible_facts.distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_facts.distribution }}.yml"
  when: distribution_config.stat.exists

- name: "Alacritty | Run WSL tasks"
  ansible.builtin.import_tasks: wsl.yml
  when: ansible_host_environment_is_wsl
