---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name }} | Stop KDE Wallet daemon"
  ansible.builtin.command:
    argv:
      - pkill
      - kwalletd6
  changed_when: networkmanager_pkill_kwalletd6.rc == 0
  failed_when: false
  register: networkmanager_pkill_kwalletd6

- name: "{{ role_name }} | Check whether gnome-keyring-daemon is running"
  ansible.builtin.command:
    argv:
      - pgrep
      - -u
      - "{{ ansible_user_id }}"
      - -f
      - gnome-keyring-daemon
  changed_when: false
  failed_when: false
  register: networkmanager_gnome_keyring_daemon_running

- name: "{{ role_name }} | Start gnome-keyring-daemon"
  ansible.builtin.command:
    argv:
      - gnome-keyring-daemon
      - --start
      - --daemonize
      - --components=secrets
  when: networkmanager_gnome_keyring_daemon_running.rc != 0

- name: "{{ role_name }} | Check whether nm-applet is running"
  ansible.builtin.command:
    argv:
      - pgrep
      - -u
      - "{{ ansible_user_id }}"
      - -f
      - nm-applet
  changed_when: false
  failed_when: false
  register: networkmanager_nm_applet_running

- name: "{{ role_name }} | Start nm-applet"
  ansible.builtin.shell:
    cmd: nm-applet &
  when: networkmanager_nm_applet_running.rc != 0

- name: "{{ role_name }} | 1Password operations"
  block:
    - name: "{{ role_name }} | List nmconnections"
      ansible.builtin.shell:
        cmd: "op item list --tags ansible/nmconnection --format json | jq -r '.[].id'"
      changed_when: false
      register: networkmanager_1password_ids_tagged_ansible
    
    - name: "{{ role_name }} | Item operations"
      ansible.builtin.include_tasks:
        file: item.yml
      loop: "{{ networkmanager_1password_ids_tagged_ansible.stdout_lines }}"
