---
- name: "{{ role_name }} | {{ ansible_facts.distribution }} | Create ~/.config/environment.d"
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/.config/environment.d"
    mode: "700"
    state: directory

- name: "{{ role_name }} | {{ ansible_facts.distribution }} | Set SSH_AUTH_SOCK"
  ansible.builtin.lineinfile:
    create: true
    dest: "{{ ansible_facts.user_dir }}/.config/environment.d/21-1password.conf"
    line: "SSH_AUTH_SOCK={{ ansible_facts.user_dir }}/.1password/agent.sock"
    mode: "644"
    regexp: "^SSH_AUTH_SOCK="
