---
- name: "{{ role_name }} | {{ ansible_distribution }} | Remove vi(m)"
  ansible.builtin.dnf:
    name:
      - vim-enhanced
    state: absent
  become: true

- name: "{{ role_name }} | {{ ansible_distribution }} | Install"
  ansible.builtin.dnf:
    name: neovim
    state: present
  become: true
