---
- name: "{{ role_name }} | Get item by ID"
  ansible.builtin.shell:
    cmd: |
      op item get {{ item }} --format json \
        | jq '{ "title": .title, "keyfile": (.fields[] | select(.label == "notesPlain").value) }'
  changed_when: false
  register: networkmanager_parsed_item

- name: "{{ role_name }} | With items representing nmconnections"
  when: networkmanager_parsed_item.stdout != ""
  block:
    - name: "{{ role_name }} | Create keyfile"
      ansible.builtin.copy:
        content: "{{ (networkmanager_parsed_item.stdout | from_json).keyfile }}"
        dest: "/etc/NetworkManager/system-connections/{{ (networkmanager_parsed_item.stdout | from_json).title }}.nmconnection"
        directory_mode: "755"
        group: root
        mode: "600"
        owner: root
      become: true
      notify: networkmanager | reload connections
