---
- name: "{{ role_name }} | {{ ansible_distribution }} | Install"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  become: true
  loop:
    - wireguard-tools
    - wireguard
