---
- name: "Wireguard | {{ ansible_facts.distribution }} | Install Wireguard"
  ansible.builtin.apt:
    name: wireguard-tools
    state: present
    update_cache: true
  become: true
  loop:
    - wireguard-tools
    - wireguard
